fix new purchase post method
when you need to add new purchase an error happened:

UnboundLocalError: local variable 'form' referenced before assignment